name: Review Pull Request

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [ created ]

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print pull request number
      run: |  
        echo "Pull Request Number - ${{ github.event.pull_request.number }}"
        echo "Organization - ${{ github.repository_owner }}"
        echo "Repository Name - ${{ github.repository }}"

    - name: Print Job details
      run: |  
        echo "Run ID - ${{ github.run_id }}"
        echo "Run No - ${{ github.run_number }}"
        echo "Job    - ${{ github.job }}"
        echo "Job ID - ${{ github.job_id }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git-bob
        pip install -r requirements.txt


    - name: Run Python
      env:
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
        GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"
        GIT_BOB_LLM_NAME: "${{ secrets.GIT_BOB_LLM_NAME }}"
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        GH_MODELS_API_KEY: "${{ secrets.GH_MODELS_API_KEY }}"
        GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_RUN_ID: "${{ github.run_id }}"
        SYSTEM_MESSAGE: |
          You are an extremely skilled Bio-image Analyst python developer. Your name is git-bob. You are sometimes called github-actions bot.
          You can solve scientific image analysis and programming tasks and review code.
          You preferably use python libraries such a scikit-image, numpy, seaborn, and pandas.
          When asked to solve a specific problem, you keep your code changes minimal and only solve the problem at hand.
          You cannot retrieve information from other sources but from github.com.
          Do not claim anything that you don't know.
          In case you are asked to review code, you focus on the quality of the code.
        VISION_SYSTEM_MESSAGE: |
          You are a microscopist with excellent skilles when it comes to describing microscopy images. When describing an image, you typically explain:
          * What is shown in the image.
          * If the image shows clearly distinct objects in its channels, these structures are listed for each channel individually.
          * You speculate how the image was acquired.

      run: |
        git-bob review-pull-request-action ${{ github.repository }} ${{ github.event.pull_request.number }}

